services:
  postgres:
    image: postgres:18-alpine
    container_name: project-nest-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestdb
    ports:
      - '5444:5432'
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
